### ISSUE TITLE
Accessoire with open/close option

### ISSUE THREAD

**Issue by sveeen** [justjam2013/homebridge-virtual-accessories#24]
Hey guys,

I found this great plugin for Homebridge.

I am looking for dummy/fake accessories which I can toggle with open and close. The standard dummy plugins only support a switch which have the states on/off.

Why I need this? I want to use Siri to open/close my bin (Hailo Libero). I want to say to Siri "Hey Siri open my bin". This doesn't work with a switch. I have to say "Hey Siri switch on my bin" which sounds horrible 🤣 

First I thought it works with the garage door, but in the home app it needs about 30 seconds until the command starts.

Do you have another idea to handle it?

**Comment by justjam2013** [comment]
> Why I need this? I want to use Siri to open/close my bin (Hailo Libero). I want to say to Siri "Hey Siri open my bin". This doesn't work with a switch. I have to say "Hey Siri switch on my bin" which sounds horrible 🤣

Indeed!

I looked through the developer documentation for Homebridge, and according to that the only accessory that I could find that specifically uses open/close states is the Garage Door. The Door, Window, and Window Covering accessories use a position of 0-100%. I would guess that that if you said `Siri, open My Window` or `Siri, open the Bedroom Blinds`, it would work as expected. But I have no idea if it would respond faster than the garage door. It would be a question to create a dummy accessory and find out.

If you want to open a ticket, at some point I can look into it, but it might be a little while before I can get to it. I just finished v1.0 of this plugin, so at the moment I am still fixing little bugs, doing some cleanup behind the scenes, and getting it verified.

**Comment by sveeen** [comment]
> The Door, Window, and Window Covering accessories use a position of 0-100%. I would guess that that if you said `Siri, open My Window` or `Siri, open the Bedroom Blinds`, it would work as expected.

Thanks for your answer. Do you have any idea how I can test it? I didn't found any way to "fake" a blind/shutter.

**Comment by justjam2013** [comment]
You could try installing `homebridge-blinds-cmd`. This plugin executes a command-line script, so you can set it up to run a simple shell script like:
```
#!/usr/bin/env bash
echo "Hello World"
```
Then name the accessory `My Blinds` and see what happens when you say `Siri, open My Blinds`.

**Comment by justjam2013** [comment]
@sveeen I just tested `homebridge-blinds-cmd`. Created `My Blinds` and said `Siri, open My Blinds` and it was successful.

**Comment by justjam2013** [comment]
I have created a virtual Window Covering (blinds) accessory, but I need finish the work on the validation branch first.

**Comment by sveeen** [comment]
Thanks for your engagement thats awesome

**Comment by justjam2013** [comment]
@sveeen I have created [v1.1.0-beta.1](https://www.npmjs.com/package/homebridge-virtual-accessories/v/1.1.0-beta.1) with a virtual window covering.
Once you install the beta, select `Window Covering - Blinds, Shades` as accessory type. In the Home app you should now be able to create an automation by selecting `An Accessory is Controlled` and picking the virtual accessory you created.
You should now be able to say `Siri, open/close <accessory name>`

Let me know if it works for you and I will merge the beta. If not, it's back to the drawing table.

On a side note, I implemented a Window Covering accessory because I was able to verify that it responds to OPEN/CLOSE. Looking at the documentation, Door and Window accessories **should** also work the same way, so if you would prefer a Door or Window icon, I can add those later.

**Comment by sveeen** [comment]
I just try it. 
Same situation like the garage door -> HomeKit apparently misses the feedback that it is really open

<img width="173" alt="image" src="https://github.com/user-attachments/assets/c5768d78-21cb-40d7-b831-ecbfc0fa4bdf">

**Comment by justjam2013** [comment]
I think it's a bug in my code then. Let me take a look at it.

**Comment by sveeen** [comment]
If you can add an option to fill in a duration (e.g. 1sec) that would be nice.

**Comment by justjam2013** [comment]
I published [1.1.0-beta.2](https://www.npmjs.com/package/homebridge-virtual-accessories/v/1.1.0-beta.2), which includes a 3 second opening/closing delay. It is hard coded right now, but if you need, I could add it as a field, so you can set the value that best matches your need.

I also fixed the Garage Door and added an opening/closing delay to it too.

**Update:** Published 1.1.1, which includes a fix in the event a transition is interrupted. For example, user presses accessory to open. Accessory transition state changes to opening. User presses widget again. Accessory transition state is interrupted and transition direction is reversed to closing.

**Comment by sveeen** [comment]
Amazing! Good work @justjam2013  - now it works as expected. ❤️ ❤️ ❤️

**Comment by justjam2013** [comment]
If it looks good, go ahead and close this bug as fixed and open a new feature request ticket.
